export const BUG_BOUNTY_VAULT_ABI = [
  { inputs: [{ internalType: "address", name: "_reputationNFT", type: "address" }], stateMutability: "nonpayable", type: "constructor" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "vaultId", type: "uint256" }, { indexed: true, internalType: "address", name: "programTeam", type: "address" }, { indexed: false, internalType: "address", name: "governanceAuthority", type: "address" }], name: "VaultCreated", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "vaultId", type: "uint256" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }, { indexed: false, internalType: "address", name: "token", type: "address" }], name: "VaultFunded", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "vaultId", type: "uint256" }, { indexed: false, internalType: "bool", name: "active", type: "bool" }], name: "VaultToggled", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "reportId", type: "uint256" }, { indexed: true, internalType: "uint256", name: "vaultId", type: "uint256" }, { indexed: true, internalType: "address", name: "researcher", type: "address" }, { indexed: false, internalType: "uint8", name: "severity", type: "uint8" }], name: "ReportSubmitted", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "reportId", type: "uint256" }, { indexed: false, internalType: "string", name: "reason", type: "string" }, { indexed: false, internalType: "uint256", name: "timestamp", type: "uint256" }], name: "ReportApproved", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "reportId", type: "uint256" }, { indexed: false, internalType: "string", name: "reason", type: "string" }], name: "ReportRejected", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "reportId", type: "uint256" }, { indexed: true, internalType: "address", name: "researcher", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "PayoutExecuted", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "reportId", type: "uint256" }, { indexed: true, internalType: "address", name: "researcher", type: "address" }, { indexed: false, internalType: "uint256", name: "tokenId", type: "uint256" }], name: "NFTMinted", type: "event" },
  { inputs: [{ internalType: "address", name: "governanceAuthority", type: "address" }, { internalType: "address", name: "rewardToken", type: "address" }, { internalType: "uint256", name: "critical", type: "uint256" }, { internalType: "uint256", name: "high", type: "uint256" }, { internalType: "uint256", name: "medium", type: "uint256" }, { internalType: "uint256", name: "low", type: "uint256" }], name: "createVault", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "vaultId", type: "uint256" }, { internalType: "uint256", name: "tokenAmount", type: "uint256" }], name: "fundVault", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "vaultId", type: "uint256" }], name: "toggleVault", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "vaultId", type: "uint256" }, { internalType: "uint8", name: "severity", type: "uint8" }, { internalType: "string", name: "ipfsHash", type: "string" }], name: "submitReport", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "reportId", type: "uint256" }, { internalType: "string", name: "reason", type: "string" }], name: "approveReport", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "reportId", type: "uint256" }, { internalType: "string", name: "reason", type: "string" }], name: "rejectReport", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "reportId", type: "uint256" }], name: "executePayout", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "reportId", type: "uint256" }, { internalType: "string", name: "tokenURI", type: "string" }], name: "mintReputationNFT", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "vaultId", type: "uint256" }], name: "getVault", outputs: [{ components: [{ internalType: "uint256", name: "id", type: "uint256" }, { internalType: "address", name: "programTeam", type: "address" }, { internalType: "address", name: "governanceAuthority", type: "address" }, { internalType: "address", name: "rewardToken", type: "address" }, { components: [{ internalType: "uint256", name: "critical", type: "uint256" }, { internalType: "uint256", name: "high", type: "uint256" }, { internalType: "uint256", name: "medium", type: "uint256" }, { internalType: "uint256", name: "low", type: "uint256" }], internalType: "struct BugBountyVault.RewardConfig", name: "rewards", type: "tuple" }, { internalType: "uint256", name: "totalFunded", type: "uint256" }, { internalType: "uint256", name: "totalPaid", type: "uint256" }, { internalType: "uint256", name: "approvedCount", type: "uint256" }, { internalType: "bool", name: "active", type: "bool" }, { internalType: "uint256", name: "createdAt", type: "uint256" }], internalType: "struct BugBountyVault.Vault", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "reportId", type: "uint256" }], name: "getReport", outputs: [{ components: [{ internalType: "uint256", name: "id", type: "uint256" }, { internalType: "uint256", name: "vaultId", type: "uint256" }, { internalType: "address", name: "researcher", type: "address" }, { internalType: "uint8", name: "severity", type: "uint8" }, { internalType: "string", name: "ipfsHash", type: "string" }, { internalType: "uint8", name: "status", type: "uint8" }, { internalType: "uint256", name: "payout", type: "uint256" }, { internalType: "uint256", name: "submittedAt", type: "uint256" }, { internalType: "uint256", name: "resolvedAt", type: "uint256" }, { internalType: "string", name: "governanceNote", type: "string" }, { internalType: "bool", name: "nftMinted", type: "bool" }], internalType: "struct BugBountyVault.Report", name: "", type: "tuple" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "vaultId", type: "uint256" }], name: "getVaultReports", outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "researcher", type: "address" }], name: "getResearcherReports", outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "vaultId", type: "uint256" }], name: "getVaultBalance", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "vaultCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "reportCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
];

export const REPUTATION_NFT_ABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "to", type: "address" }, { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" }, { indexed: false, internalType: "string", name: "tokenURI", type: "string" }], name: "ReputationMinted", type: "event" },
  { inputs: [{ internalType: "address", name: "_minterContract", type: "address" }], name: "setMinterContract", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "to", type: "address" }, { internalType: "string", name: "_tokenURI", type: "string" }], name: "mintTo", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "totalSupply", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "tokenCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }], name: "tokenURI", outputs: [{ internalType: "string", name: "", type: "string" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }], name: "ownerOf", outputs: [{ internalType: "address", name: "", type: "address" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "owner", type: "address" }], name: "balanceOf", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
];

export const VAULT_ADDRESS = process.env.NEXT_PUBLIC_VAULT_CONTRACT_ADDRESS;
export const NFT_ADDRESS = process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS;
